### ISSUE TITLE
Does not work on Windows 10 with docker installed

### ISSUE THREAD

**Issue by thinkinsysdev** [bradyholt/aspnet-core-react-template#13]
Thank you for this awesome template! Works like a charm for development on the mac!
I was trying to run this on Windows 10 with docker installed.
Cloned the repo
Ran npm install 
Then npm start
It failed with the following errors 

> C:\Users\LabAdmin\dotnet\aspnet-core-react-template-master>npm start

> aspnet.core.react.template@1.0.0 prestart C:\Users\LabAdmin\dotnet\aspnet-core-react-template-master
> docker-compose up -d

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 118, in perform_command
  File "compose\cli\main.py", line 926, in up
  File "compose\project.py", line 388, in up
  File "compose\project.py", line 614, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 90, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 183, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
Failed to execute script docker-compose

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! aspnet.core.react.template@1.0.0 prestart: `docker-compose up -d`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the aspnet.core.react.template@1.0.0 prestart script 'docker-compose up -d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aspnet.core.react.template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     docker-compose up -d
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aspnet.core.react.template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aspnet.core.react.template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\LabAdmin\dotnet\aspnet-core-react-template-master\npm-debug.log

C:\Users\LabAdmin\dotnet\aspnet-core-react-template-master>

**Comment by bradyholt** [comment]
I do not have access to a Windows 10 box currently and would appreciate if you could help get to the bottom of this issue. This issue looks simular: https://github.com/shipping-docker/php-app/issues/19 .  Do you think you could follow the resolution steps mentioned in there and see if you can get it to work?

**Comment by thinkinsysdev** [comment]
I found the error - it was on my part - docker was not running.
